### ISSUE TITLE
Decider class

### ISSUE THREAD

**Issue by amandakrohn** [darkway-s/SE-Group10#21]
Create Decider class.

Is responsible for instantiate all necessary classes and to make the calculations.

**From lab description:**
DECIDE() will generate a boolean signal which determines whether an interceptor should be
launched based upon input radar tracking information. 

**Dependencies:**
- conditions met vector (#9)
- preliminary unlocking matrix (#7)
- final unlocking vector (#16)
- parameter manager (#22)

**TODO:**
- [x] Decider class
- [ ] Tests for Decider class

[Class diagram](https://drive.google.com/file/d/1KWa893xuObUJYNH05qSMQeP5j4YMa4E8/view?usp=sharing )

**Comment by BrorSebastianSjovald** [comment]
Decider class is implemented but not tested. Re-opening the issue.
