### ISSUE TITLE
Parameter manager

### ISSUE THREAD

**Issue by amandakrohn** [darkway-s/SE-Group10#22]
Create ParameterManager class 

Takes input from a file and stores all the parameters (numPoints, points, licParameters, LCM, PUV). The parameters should be converted to the appropriate type (int, Point[], int[][], LICParamter, etc). Their type is defined in the lab description except points and licParameters which have the type Point[] and LICParameter respectively.

- [ ] function for reading input
- [ ] function(s) for parsing the input

**Comment by Sefik-Palazoglu** [comment]
Some comments:

- We do not need to store NUMPOINTS input, we just use it the first time we are taking input.
- Where should we store the parameters. Does this class store them inside itself? Then we reach the parameters from DECIDE class by invoking something like ParameterManager.getLIC(...)?
- Do we take input from the STDIN?
- What should we take as input? Input file name or input itself?
