### ISSUE TITLE
Point class

### ISSUE THREAD

**Issue by amandakrohn** [darkway-s/SE-Group10#24]
Create Point class.

Should define a point (x, y) in the plane.

**Comment by darkway-s** [comment]
It has already been done in commit “Initialize code skeleton, feat #1“  on Jan 31, 2022 by @BrorSebastianSjovald

**Comment by amandakrohn** [comment]
I do not think that the class can be used as intended and thus we should _re-open the issue_. One is not able to instantiate a Point-object with attributes x and y. The class should look something like this:
```
public class Point{
  public Point(int x, int y){
    /* constructor body omitted */
  }
  
  public Point getPoint(){
   /* method body omitted */  
  }

  /* maybe other useful methods, such as distanceTo(), toString()*/
}
```

**Comment by BrorSebastianSjovald** [comment]
distranceTo() seems like a great function. It should probably take in another object of Point class and calculate euclidean distance
