### ISSUE TITLE
Launch interceptor progam class

### ISSUE THREAD

**Issue by amandakrohn** [darkway-s/SE-Group10#25]
Create LaunchInterceptorProgram class.

- [x] main function

Dependencies:
- Decider (#21)

**Comment by ludwigjo** [comment]
The method is implemented but we should test this before merge

**Comment by darkway-s** [comment]
I think we need more functions to output the intermediate results. But I'm not quite sure if we should print it. The decide.pdf just says "the following intermediate results are computed."

**Comment by ludwigjo** [comment]
Alright, what other functions do you have in mind? @darkway-s  It says in the pdf that "Final launch / no launch decision encoded as ”YES”, ”NO” on the standard output." So i think it's fine to just print it out.

**Comment by BrorSebastianSjovald** [comment]
I think it is enough that we print YES or NO. We can extract intermediate results in the `decide()` function if we need to.
