### ISSUE TITLE
Connectors enum

### ISSUE THREAD

**Issue by amandakrohn** [darkway-s/SE-Group10#26]
Create Connectors enum that defines ANDD, ORR, NOTUSED

**Comment by darkway-s** [comment]
What else should we do on Connectors?

**Comment by amandakrohn** [comment]
@darkway-s Notihing! We just need to define the enum as such:
```
public enum Connector {
    ANDD,
    ORR, 
    NOTUSED; 
}
```
and then they are ready to be used with: `Connector.ANDD` etc.

**Comment by Sefik-Palazoglu** [comment]
Where is the commit which accomplishes this? so we can close it with linking it.

**Comment by Sefik-Palazoglu** [comment]
I linked it with the initial PR since it is the place where we add the enum Connector. Closing this issue now.
