### ISSUE TITLE
Preliminary unlocking matrix

### ISSUE THREAD

**Issue by amandakrohn** [darkway-s/SE-Group10#7]
Create PreliminaryUnlockingMatrix class

**From the lab description:**
The combination of LCM and CMV is stored in the Preliminary Unlocking Matrix (PUM), a 15x15 symmetric matrix.

The entries in the LCM represent the logical connectors to be used between pairs of LICs to determine the corresponding entry in
the PUM, i.e. LCM[i,j] represents the boolean operator to be applied to CMV[i] and CMV[j]. PUM[i,j] is set according to the result of this operation. If LCM[i,j] is NOTUSED, then PUM[i,j] should be set to true. If LCM[i,j] is ANDD, PUM[i,j] should be set to true only if (CMV[i] AND CMV[j]) is true. If LCM[i,j] is ORR, PUM[i,j] should be set to true if (CMV[i] OR CMV[j]) is true. (Note that the LCM is symmetric, i.e. LCM[i,j]=LCM[j,i] for all i and j.)

**Ex**:  PUM[0,2] is true because LCM[0,2] is ORR, and at least one of CMV[0] and CMV[2] is true

- [ ] setPreliminaryUnlockingMatrix
- [ ] getPreliminaryUnlockingMatrix
- [ ] other functionality needed

**Dependencies**:
- conditions met vector (#9)

[Class diagram](https://drive.google.com/file/d/1KWa893xuObUJYNH05qSMQeP5j4YMa4E8/view?usp=sharing )

**Comment by BrorSebastianSjovald** [comment]
Is it okay if I take over this issue? In order to distribute the work evenly. You have done a great deal on #23 and #40. Plus our three CMV issues. You don't need to take on more work I think.

**Comment by BrorSebastianSjovald** [comment]
Taking over issue!
