### ISSUE TITLE
Refactoring needed for ConditionsMetVector class

### ISSUE THREAD

**Issue by Sefik-Palazoglu** [darkway-s/SE-Group10#73]
I have a proposition about our ConditionsMetVector Class @channel !

- Get rid of the length field since now we have length() method for Vector’s
- Get rid of pm field. But still keep the pm’s inside the constructor.
- Keep only the ConditionsMetVector(ParameterManager pm) constructor. This way, the only way to create a CMV, is by providing it a ParameterManager. And in this constructor, use the LIC*() functions we wrote to populate the conditionsMetVector field.
- I suggest this way of doing this, because if we do this, the only way to create a CMV, is the “right way”

**Comment by amandakrohn** [comment]
Make the LIC_X methods static. It does not really make any sense to have them connected to a class.
In the CMV constructor we can then call these static methods to populate the CMV.
