### ISSUE TITLE
Conditions Met Vector (CMV) class

### ISSUE THREAD

**Issue by BrorSebastianSjovald** [darkway-s/SE-Group10#9]
Create the ConditionsMetVector.class

### Description of CMV
The __*Conditions Met Vector*__ (CMV) should be set according to the results of these calculations, i. e. the global array __CMV[i]__ should be set to true if and only if the i'th LIC is met. The 15 __*Launch Interceptor Conditions*__ (LIC) are defined in the 15 following issues:

- [x] #2  
- [x] #3  
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #8 
- [x] #10 
- [x] #11 
- [x] #12 
- [x] #14 
- [x] #15 
- [x] #17 
- [x] #18 
- [x] #19  
- [x] #20

**Comment by darkway-s** [comment]
There is still a need for the refractor of current CMV class. It would be closed after #73 was closed.

**Comment by darkway-s** [comment]
refractor finished #73 !
Thanks for everyone's contribution !
